[phases.setup]
nixPkgs = ["nginx"]

[phases.install]
cmds = [
  "mkdir -p /etc/nginx /var/log/nginx /var/cache/nginx"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "cp nginx.conf /etc/nginx/nginx.conf",
  "ls -la /app/assets"  # Debug: List assets directory
]

[start]
cmd = "nginx -g 'daemon off;'"