[phases.setup]
nixPkgs = ["nginx"]

[phases.install]
cmds = [
  "mkdir -p /etc/nginx/conf.d /var/log/nginx /var/cache/nginx",
  "mkdir -p /usr/share/nginx/html"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "cp -r * /usr/share/nginx/html/",
  "cp nginx.conf /etc/nginx/conf.d/default.conf"
]

[start]
cmd = "nginx -g 'daemon off;'"