[phases.setup]
nixPkgs = ["nginx"]

[phases.install]
cmds = [
  "mkdir -p /etc/nginx /var/log/nginx /var/cache/nginx"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "cp nginx.conf /etc/nginx/nginx.conf",
  "ls -la /app",          # Debug: List root directory
  "ls -la /app/assets",   # Debug: List assets directory
  "cat /app/index.html"   # Debug: Show index.html content
]

[start]
cmd = "nginx -g 'daemon off;'"