[phases.setup]
nixPkgs = ["nginx"]

[phases.install]
cmds = [
  "mkdir -p /etc/nginx /var/log/nginx /var/cache/nginx"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "cp nginx.conf /etc/nginx/nginx.conf",
  "echo 'Checking assets directory:'",
  "ls -la /app/assets/",
  "chmod -R 755 /app",
  "echo 'Verifying file permissions:'",
  "ls -la /app/"
]

[start]
cmd = "nginx -g 'daemon off;'"