[phases.setup]
nixPkgs = ["nginx"]

[phases.install]
cmds = [
  "mkdir -p /etc/nginx /var/log/nginx /var/cache/nginx"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "cp nginx.conf /etc/nginx/nginx.conf",
  "echo '=== Checking source files ==='",
  "ls -la assets/",
  "echo '=== Creating app directory ==='",
  "mkdir -p /app/assets",
  "echo '=== Copying assets ==='",
  "cp -v assets/* /app/assets/",
  "echo '=== Checking copied files ==='",
  "ls -la /app/assets/",
  "chmod -R 755 /app"
]

[start]
cmd = "nginx -g 'daemon off;'"