[phases.setup]
nixPkgs = ["nginx"]

[phases.install]
cmds = [
  "mkdir -p /etc/nginx /var/log/nginx /var/cache/nginx"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "cp nginx.conf /etc/nginx/nginx.conf",
  "mkdir -p /app/assets",
  "cp -f assets/* /app/assets/ || true",
  "chmod -R 755 /app"
]

[start]
cmd = "nginx -g 'daemon off;'"