[phases.setup]
nixPkgs = ["nginx"]

[phases.build]
cmds = [
  "mkdir -p /etc/nginx /var/log/nginx /var/cache/nginx",
  "cp nginx.conf /etc/nginx/nginx.conf"
]

[start]
cmd = "nginx -g 'daemon off;'"

[nginx]
root = "/app"